<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.1" />
    <PackageReference Include="xunit.v3.mtp-v2" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Sylvercode.SiteExtractor\Sylvercode.SiteExtractor.csproj" />
    <ProjectReference Include="..\..\src\Sylvercode.SiteExtractor.Markdown\Sylvercode.SiteExtractor.Markdown.csproj" />
    <ProjectReference Include="..\Sylvercode.SiteExtractor.Tests\Sylvercode.SiteExtractor.Tests.csproj" />
    <ProjectReference Include="..\Sylvercode.StructDocExtractor.Tests\Sylvercode.StructDocExtractor.Tests.csproj" />
  </ItemGroup>

</Project>
