<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../Sylvercode.SiteExtractor/Sylvercode.SiteExtractor.csproj" />
    <ProjectReference Include="..\Sylvercode.SiteExtractor.StdHtml\Sylvercode.SiteExtractor.StdHtml.csproj" />
    <ProjectReference Include="..\Sylvercode.StructDocExtractor.AngleSharp\Sylvercode.StructDocExtractor.AngleSharp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="1.8.1" />
    <PackageReference Include="AngleSharp.Io" Version="1.1.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <AnalysisMode>Recommended</AnalysisMode>
  </PropertyGroup>

</Project>
